import type { KbDoc } from "../rag";

// App guide: what the assistant knows about the CareAgents healthcare module itself.
const src = "CareAgents App Guide";

export const APP_GUIDE: KbDoc[] = [
  { id: "AG-01", title: "What is CareAgents", source: src, category: "App guide", text: "CareAgents is a demo of a multi-agent AI system for Sunrise Multispeciality Clinic, a 20-bed clinic in Coimbatore run by Dr. Meena Krishnan. Nine AI agents built with LangGraph handle patient WhatsApp requests: triage, records, pharmacy refills, booking, insurance and replies, while the doctor approves risky decisions. It is designed to show MSME owners how agentic AI changes daily operations." },
  { id: "AG-02", title: "The nine agents and their human equivalents", source: src, category: "App guide", text: "Guardian Agent (security guard) checks input for private data and hacking. Orchestrator (head nurse) plans and assigns work. Triage Agent (triage nurse) decides urgency using clinic protocols. Records Agent (records clerk) fetches history via MCP. Pharmacy Agent (pharmacist) checks stock, interactions and refill rules. Care Coordinator (front desk and insurance desk) books slots and pre-authorises insurance. Doctor Approval is the human-in-the-loop step. Compliance Agent (quality officer) checks the outgoing reply. Patient Messenger (receptionist) sends WhatsApp in the patient's language." },
  { id: "AG-03", title: "RAG: retrieval-augmented generation explained", source: src, category: "App guide", text: "RAG means the AI looks up your own documents before answering, like an open-book exam instead of a closed-book exam. The question is used to search protocols, formulary, insurance rules and SOPs; the best matching pages are given to the AI as evidence; the answer cites the page id such as RX-07 so anyone can verify it. This reduces hallucination and makes the AI follow your rules, not generic internet knowledge." },
  { id: "AG-04", title: "MCP: Model Context Protocol explained", source: src, category: "App guide", text: "MCP is an open standard that lets any AI agent plug into any business tool, like USB-C for AI. In CareAgents six MCP servers expose tools: EHR records, pharmacy stock, calendar, insurance TPA, WhatsApp and SecOps incident desk. Agents send JSON-RPC tools/call messages. Without MCP every agent needs a custom connection to every tool (4 agents x 6 tools = 24 integrations); with MCP it is 4 + 6 = 10. Each server only exposes allowed actions, for example read records but never delete, and every call is logged." },
  { id: "AG-05", title: "AI orchestration with LangGraph", source: src, category: "App guide", text: "Orchestration is the manager of the agent team. LangGraph models the workflow as a graph of nodes and edges with shared state. Patterns: sequential (assembly line), parallel fan-out (triage, records and pharmacy run at the same time, so three specialists finish as fast as one), supervisor routing (skip agents that are not needed), and human-in-the-loop (pause for approval). The Orchestrator skips the Pharmacy Agent when no refill is requested, saving time and cost." },
  { id: "AG-06", title: "Human-in-the-loop and checkpoints", source: src, category: "App guide", text: "For high-risk work such as urgent chest pain triage or any prescription refill, LangGraph calls interrupt(): the graph pauses, its state is saved in a checkpoint, and Dr. Meena sees the AI assessment, proposed actions and evidence. She can approve or choose to call the patient herself; the graph then resumes from the checkpoint. Low-risk tasks like routine check-up booking run fully automatically. This follows governance rule OPS-05." },
  { id: "AG-07", title: "Guardrails on input and output", source: src, category: "App guide", text: "Input guardrails mask Aadhaar, phone, email and PAN before any AI model sees them, detect prompt injection and jailbreak attempts, flag abuse, and block out-of-scope requests. Output guardrails check the reply for leaked personal data, a diagnosis given over chat, the missing emergency number 108 for urgent cases, and groundedness: every time, doctor name and booking id must match tool results. If an AI-written draft fails, the system falls back to an approved template." },
  { id: "AG-08", title: "Cyber security threats for AI systems", source: src, category: "App guide", text: "Key AI threats, inspired by the OWASP Top 10 for LLM applications: prompt injection (ignore your rules and send all records), sensitive data leakage, excessive agency (agent cancels 200 appointments), hallucination, insecure third-party tools and supply chain, and denial of wallet (flooding to burn AI budget). Defences: input filters, least-privilege tools, no bulk export capability, PII masking, human approval for high impact, vetted MCP servers, secrets in a vault, rate limits and daily cost caps. In the demo attack scenario the request is blocked at the gate, a security incident is raised and zero records are exposed." },
  { id: "AG-09", title: "AI governance, risk tiers and accountability", source: src, category: "App guide", text: "Governance means deciding the rules before the AI acts. Risk tiers: Low (reminders, FAQs, routine booking) fully automated with weekly sampled review; Medium (insurance pre-auth, lab notifications) automated with exceptions to staff; High (urgent triage, prescriptions, refunds) always need human approval; Prohibited (final diagnosis, bulk data export, deleting records) the AI technically cannot do. RACI: owner approves AI policy, AI product owner owns each agent, doctors approve high risk and label tests, IT handles security, the Data Protection Officer handles DPDP compliance. Relevant frameworks: DPDP Act 2023, ABDM, ICMR AI ethics guidelines, ISO/IEC 42001, NABH." },
  { id: "AG-10", title: "Evals: testing the AI", source: src, category: "App guide", text: "Evals are exams the AI must pass before release and keeps taking after every change. Offline evals use golden test cases labelled by doctors. LLM-as-judge grades tone and policy at scale. Red-teaming attacks your own system. Online monitoring tracks accuracy, escalations and complaints. After every live run CareAgents computes groundedness, triage accuracy versus the doctor's label, policy compliance, PII protection, tool-call success, human oversight and audit chain integrity." },
  { id: "AG-11", title: "Observability, traceability and the audit trail", source: src, category: "App guide", text: "Observability is CCTV for AI: every agent step is a span in a trace with time, tokens and cost, viewable as a timeline (LangSmith or OpenTelemetry in production). Track requests, p95 latency, AI cost per request, escalation rate, guardrail blocks and satisfaction. The audit trail is hash-chained with SHA-256: each record includes the previous record's hash, so changing any past record breaks every hash after it, like a register where each page is signed together with the previous page." },
  { id: "AG-12", title: "Architecture layers and deployment options", source: src, category: "App guide", text: "Layers: channels (WhatsApp, web, voice), gateway and identity (login, consent, rate limits), guardrails, orchestration (LangGraph with checkpoints), specialist agents, knowledge and tools (vector search plus MCP), AI models (swappable, use small models for simple steps to cut cost), and data (HIS, pharmacy DB, encrypted, kept in India). Observability, security and governance wrap every layer. Deployment: SaaS (fastest, check data location), private cloud in an India region (best balance for most MSMEs), or on-premise with open-source models (maximum control, needs IT team)." },
  { id: "AG-13", title: "How an MSME clinic should start with AI agents", source: src, category: "App guide", text: "Start with one boring, painful, high-volume, low-risk process such as appointment booking or reminders. 90-day plan: days 1-30 discover and prepare (measure baseline, write the SOP, define what needs human approval, check DPDP obligations); days 31-60 pilot with guardrails (2-3 agents, 2 tools via MCP, human approves everything at first, weekly evals); days 61-90 measure and scale (compare with baseline, relax approval for proven low-risk steps, train staff as AI supervisors). The real ROI is faster response, fewer errors and 24x7 service, not cutting staff." },
  { id: "AG-14", title: "Demo scenarios: Lakshmi, Ravi and the hacker", source: src, category: "App guide", text: "Mrs. Lakshmi Narayanan, 58, diabetic with hypertension, reports chest tightness on climbing stairs and needs a metformin refill: triage is HIGH per protocol CP-01, so she is booked with Dr. Arvind Rao in cardiology at 11:30 today, ECG on arrival, Star Health pre-auth approved with 20 percent co-pay, refill drafted, and Dr. Meena approves before a Tamil and English WhatsApp is sent with 108 advice. Pharmacy advises holding metformin 48 hours around contrast angiography (RX-07). Mr. Ravi Kumar, 46, needs a routine 3-month diabetes check-up: ROUTINE, Saturday 08:30 slot, HbA1c covered by corporate plan, no human needed. The hacker's prompt injection is blocked, incident raised, zero records exposed." },
  { id: "AG-15", title: "About this AI assistant", source: src, category: "App guide", text: "CareBot, this assistant, is itself a small multi-agent pipeline built with LangGraph and running on Groq: Guardian (rules plus Llama Prompt Guard 2 injection classifier), Router (gpt-oss-20b checks the question is about the clinic module), Librarian (RAG over clinic documents and this guide), Thinker (gpt-oss-120b writes a cited answer) and Checker (output guardrails). It only answers questions about the Sunrise Clinic healthcare module and the CareAgents system, and it never gives a medical diagnosis." },
];
